jobs:
  - name: Build and Deploy
    steps:
      - name: Download wkhtmltopdf
        run: |
          wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.bionic_amd64.deb -O wkhtmltox.deb
          dpkg -i wkhtmltox.deb
      - name: Build Go App
        run: go build -o main .
      - name: Railway Up
        run: railway up