services:
  - name: web
    env: nodejs12
    github: railwayapp/starters
    scale: 1
    build:
      env:
        BASE_PATH: /mnt/server

# Define the custom dependency
dependencies:
  # Custom dependency for wkhtmltopdf
  - name: wkhtmltopdf
    install:
      # You can provide installation steps here
      - RUN wget -q -O - https://packagecloud.io/gpg.key | apt-key add -
      - RUN echo 'deb http://download.opensuse.org/repositories/home:/melkorion/xUbuntu_20.04/ /' > /etc/apt/sources.list.d/home:melkorion.list
      - RUN apt update && apt install -y wkhtmltopdf
