name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x

      - name: Build and Deploy
        run: |
          go build -o andalalin
          scp -r andalalin user@droplet-ip:/var/www/andalalin
          ssh root@165.22.61.62 'cd /var/www/andalalin && ./andalalin'
