name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-qemu-action@v2

    - name: Build and push Docker image
      run: |
        docker build -t andalalin .
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker tag andalalin ${{ secrets.DOCKER_USERNAME }}/andalalin:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/andalalin:latest

    - name: SSH into Droplet and redeploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.DROPLET_USERNAME }}
        key: |
      -----BEGIN OPENSSH PRIVATE KEY-----
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCKQ/vhI+IdZMrLE7iPsmPPcARq09deCmn4bMYacmmKnId46PJVkDRI170dmhS/NQSQ9O3viRgZddxIV37VdTCZqycCHuXBAHmSoWShcH1hQaahMAfiXWOYfDbsZvR5nvdUkUzaAHeQO9IeQAl1aak4HQ4qpQpLew5TkM+2gEKpnOkHTgbqxKWBEVe+1Weqh9IaqyA91O9FnO/B5G7ewZnViYyBzdIM+fSZgaM1o1lCVYn4jZRO12EbM6Z7Bj3USAIZ+Ezkj32WZWmMFRIMiGDcPgivtwhhjfZpro+xugoC9yecGa3w3FbE9HXorcSKaiGST2dhDNjYZ/jlWUf98KmL rsa-key-20231214
      -----END OPENSSH PRIVATE KEY-----
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/andalalin:latest
          docker stop andalalin || true
          docker rm andalalin || true
          docker run -d -p 8080:8080 --name andalalin ${{ secrets.DOCKER_USERNAME }}/andalalin:latest
