name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1  
      with:
        driver-opts: image=moby/buildkit:v0.9.0 

    - name: Build and push Docker image
      uses: docker/build-push-action@v2.7.0
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/andalalin:latest

deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: SSH into Droplet and redeploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.DROPLET_USERNAME }}
        key: ${{ secrets.DROPLET_SSH_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/andalalin:latest
          docker kill andalalin || true
          docker rm andalalin || true
          docker run -d -p 8080:8080 --name andalalin ${{ secrets.DOCKER_USERNAME }}/andalalin:latest
